//! Port of `decompiler/cpp/error.hh` plus the exception subclasses scattered
//! through the C++ tree (W1) — the error model of ADR 0004.
//!
//! C++ throws `LowlevelError` and subclasses and catches them at a small
//! number of well-known frames.  The Rust port returns
//! `Result<T, KunaError>` and matches at the same frames.  Variants mirror
//! the C++ hierarchy one-to-one:
//!
//! | variant            | C++ type                | declared in     |
//! |--------------------|-------------------------|-----------------|
//! | `Lowlevel`         | `LowlevelError`         | `error.hh`      |
//! | `Recov`            | `RecovError`            | `error.hh`      |
//! | `Parse`            | `ParseError`            | `error.hh`      |
//! | `Decoder`          | `DecoderError`          | `xml.hh` (used by `marshal.hh`) |
//! | `Sleigh`           | `SleighError`           | `context.hh`    |
//! | `Unimpl`           | `UnimplError`           | `translate.hh`  |
//! | `BadData`          | `BadDataError`          | `translate.hh`  |
//! | `DataUnavail`      | `DataUnavailError`      | `loadimage.hh`  |
//! | `Evaluation`       | `EvaluationError`       | `opbehavior.hh` |
//! | `ParamUnassigned`  | `ParamUnassignedError`  | `fspec.hh`      |
//! | `JumptableThunk`   | `JumptableThunkError`   | `jumptable.hh`  |
//! | `Java`             | `JavaError`             | `ghidra_arch.hh`|
//!
//! IMPORTANT inheritance detail carried over from C++: `DecoderError` is a
//! standalone struct, **not** derived from `LowlevelError`.  A C++ frame
//! catching `LowlevelError` does *not* catch `DecoderError`; ported catch
//! frames must use [`KunaError::is_lowlevel`] to reproduce that distinction.
//!
//! `DuplicateFunctionError` (`database.hh`, a `RecovError` carrying an
//! `Address` + function name) is intentionally deferred to the database wave:
//! its payload needs the `Address` type, which is not yet ported.  Adding it
//! is an additive variant, not a reshape.
//!
//! `panic!` is reserved for internal invariant violations (states the C++
//! code treats as undefined behavior or asserts on); panics are never used
//! for recoverable engine errors and never caught.

use thiserror::Error;

/// Convenience alias for fallible engine code (ADR 0004).
pub type KunaResult<T> = core::result::Result<T, KunaError>;

/// The decompiler error hierarchy as a single enum (see module docs).
///
/// `Display` renders the bare explanatory string, exactly like reading the
/// C++ `explain` member; catch-frame prefixes ("Low-level ERROR: ", ...) are
/// added at the frames that print, not here.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum KunaError {
    /// C++ `LowlevelError`: the lowest level error generated by the
    /// decompiler.  The underived form is thrown for very low level errors
    /// that immediately abort decompilation (usually for just a single
    /// function).
    #[error("{explain}")]
    Lowlevel {
        /// Explanatory string
        explain: String,
    },

    /// C++ `RecovError`: the most basic form of recoverable error, meaning
    /// there is some problem that the user did not take into account.
    #[error("{explain}")]
    Recov {
        /// Explanatory string
        explain: String,
    },

    /// C++ `ParseError`: generated when parsing character data of some form,
    /// as in a user command from the console or when parsing C syntax.
    #[error("{explain}")]
    Parse {
        /// Explanatory string
        explain: String,
    },

    /// C++ `DecoderError` (`xml.hh`): thrown by the XML parser / stream
    /// decoders (`marshal.hh`).  NOT part of the `LowlevelError` hierarchy.
    #[error("{explain}")]
    Decoder {
        /// Explanatory string
        explain: String,
    },

    /// C++ `SleighError` (`context.hh`): exception thrown by the SLEIGH
    /// engine.
    #[error("{explain}")]
    Sleigh {
        /// Explanatory string
        explain: String,
    },

    /// C++ `UnimplError` (`translate.hh`): a particular machine instruction
    /// was valid but cannot be translated into p-code.
    #[error("{explain}")]
    Unimpl {
        /// Explanatory string
        explain: String,
        /// Number of bytes in the unimplemented instruction (C++
        /// `instruction_length`, an `int4`).
        instruction_length: i32,
    },

    /// C++ `BadDataError` (`translate.hh`): the system cannot decode data
    /// for a particular instruction — usually not really a machine
    /// instruction.
    #[error("{explain}")]
    BadData {
        /// Explanatory string
        explain: String,
    },

    /// C++ `DataUnavailError` (`loadimage.hh`): a request for load image
    /// data cannot be met, usually because the requested address range is
    /// not in the image.
    #[error("{explain}")]
    DataUnavail {
        /// Explanatory string
        explain: String,
    },

    /// C++ `EvaluationError` (`opbehavior.hh`): emulation evaluation of an
    /// operator failed (forward or reverse emulation).
    #[error("{explain}")]
    Evaluation {
        /// Explanatory string
        explain: String,
    },

    /// C++ `ParamUnassignedError` (`fspec.hh`): a prototype can't be modeled
    /// properly.
    #[error("{explain}")]
    ParamUnassigned {
        /// Explanatory string
        explain: String,
    },

    /// C++ `JumptableThunkError` (`jumptable.hh`): a thunk mechanism that
    /// looks like a jump-table.
    #[error("{explain}")]
    JumptableThunk {
        /// Explanatory string
        explain: String,
    },

    /// C++ `JavaError` (`ghidra_arch.hh`): an exception from the Ghidra
    /// client (or generated for protocol alignment) to be sent back to it.
    #[error("{explain}")]
    Java {
        /// The name of the Java exception class (C++ field `type`).
        type_name: String,
        /// Explanatory string
        explain: String,
    },
}

impl KunaError {
    /// `throw LowlevelError(s)`
    pub fn lowlevel(s: impl Into<String>) -> Self {
        KunaError::Lowlevel { explain: s.into() }
    }

    /// `throw RecovError(s)`
    pub fn recov(s: impl Into<String>) -> Self {
        KunaError::Recov { explain: s.into() }
    }

    /// `throw ParseError(s)`
    pub fn parse(s: impl Into<String>) -> Self {
        KunaError::Parse { explain: s.into() }
    }

    /// `throw DecoderError(s)`
    pub fn decoder(s: impl Into<String>) -> Self {
        KunaError::Decoder { explain: s.into() }
    }

    /// `throw SleighError(s)`
    pub fn sleigh(s: impl Into<String>) -> Self {
        KunaError::Sleigh { explain: s.into() }
    }

    /// `throw UnimplError(s, l)`
    pub fn unimpl(s: impl Into<String>, instruction_length: i32) -> Self {
        KunaError::Unimpl { explain: s.into(), instruction_length }
    }

    /// `throw BadDataError(s)`
    pub fn bad_data(s: impl Into<String>) -> Self {
        KunaError::BadData { explain: s.into() }
    }

    /// `throw DataUnavailError(s)`
    pub fn data_unavail(s: impl Into<String>) -> Self {
        KunaError::DataUnavail { explain: s.into() }
    }

    /// `throw EvaluationError(s)`
    pub fn evaluation(s: impl Into<String>) -> Self {
        KunaError::Evaluation { explain: s.into() }
    }

    /// `throw ParamUnassignedError(s)`
    pub fn param_unassigned(s: impl Into<String>) -> Self {
        KunaError::ParamUnassigned { explain: s.into() }
    }

    /// `throw JumptableThunkError(s)`
    pub fn jumptable_thunk(s: impl Into<String>) -> Self {
        KunaError::JumptableThunk { explain: s.into() }
    }

    /// `throw JavaError(tp, message)`
    pub fn java(type_name: impl Into<String>, s: impl Into<String>) -> Self {
        KunaError::Java { type_name: type_name.into(), explain: s.into() }
    }

    /// The explanatory string — C++ `LowlevelError::explain` /
    /// `DecoderError::explain`.
    pub fn explain(&self) -> &str {
        match self {
            KunaError::Lowlevel { explain }
            | KunaError::Recov { explain }
            | KunaError::Parse { explain }
            | KunaError::Decoder { explain }
            | KunaError::Sleigh { explain }
            | KunaError::Unimpl { explain, .. }
            | KunaError::BadData { explain }
            | KunaError::DataUnavail { explain }
            | KunaError::Evaluation { explain }
            | KunaError::ParamUnassigned { explain }
            | KunaError::JumptableThunk { explain }
            | KunaError::Java { explain, .. } => explain,
        }
    }

    /// Would a C++ `catch (const LowlevelError &)` frame catch this?
    ///
    /// True for every variant except [`KunaError::Decoder`], which in C++ is
    /// a standalone struct outside the `LowlevelError` hierarchy.
    pub fn is_lowlevel(&self) -> bool {
        !matches!(self, KunaError::Decoder { .. })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_error_display_is_bare_explain() {
        let e = KunaError::lowlevel("Restarting decompilation");
        assert_eq!(e.to_string(), "Restarting decompilation");
        assert_eq!(e.explain(), "Restarting decompilation");
        let e = KunaError::unimpl("Unable to translate instruction", 4);
        assert_eq!(e.to_string(), "Unable to translate instruction");
        match e {
            KunaError::Unimpl { instruction_length, .. } => assert_eq!(instruction_length, 4),
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn test_error_decoder_outside_lowlevel_hierarchy() {
        // catch(LowlevelError) in C++ catches all subclasses ...
        assert!(KunaError::lowlevel("x").is_lowlevel());
        assert!(KunaError::recov("x").is_lowlevel());
        assert!(KunaError::parse("x").is_lowlevel());
        assert!(KunaError::sleigh("x").is_lowlevel());
        assert!(KunaError::unimpl("x", 0).is_lowlevel());
        assert!(KunaError::bad_data("x").is_lowlevel());
        assert!(KunaError::data_unavail("x").is_lowlevel());
        assert!(KunaError::evaluation("x").is_lowlevel());
        assert!(KunaError::param_unassigned("x").is_lowlevel());
        assert!(KunaError::jumptable_thunk("x").is_lowlevel());
        assert!(KunaError::java("IOException", "x").is_lowlevel());
        // ... but NOT DecoderError, which is not derived from it.
        assert!(!KunaError::decoder("Unexpected end of stream").is_lowlevel());
    }

    #[test]
    fn test_error_java_carries_class_type() {
        let e = KunaError::java("java.lang.IllegalArgumentException", "bad arg");
        match &e {
            KunaError::Java { type_name, explain } => {
                assert_eq!(type_name, "java.lang.IllegalArgumentException");
                assert_eq!(explain, "bad arg");
            }
            _ => panic!("wrong variant"),
        }
    }
}
