#!/usr/bin/env python3
"""
regen_golden.py — one-command, reproducible Ghidra golden-output regeneration.

Drives Ghidra's analyzeHeadless to decompile a binary, writing the C output
straight to a file (via the patched ghidra_decompile_all.py postScript) so C
text never interleaves with Ghidra's INFO log lines.

Why this exists: tests/golden/ghidra_curl.c (11.3.2 era) was generated by
hand-running analyzeHeadless and capturing stdout, which (a) had no working
documented command, (b) required manual "strip first 124 lines" cleanup, and
(c) shipped 4 trailing INFO lines contaminating the golden. This script makes
regen a single deterministic command.

Usage:
    python tools/regen_golden.py --binary examples/curl
    python tools/regen_golden.py --binary examples/httpd --output tests/golden/ghidra_httpd.c
    python tools/regen_golden.py --binary examples/curl --keep-project   # debug

Exit codes: 0 on success, 1 on any failure (bad output, Ghidra crash, empty file).
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path

# Default search list for analyzeHeadless. The 12.1 source repo at
# D:/ghidra/rugra/ghidra is NOT built and cannot run headless, so this is only
# a fallback — pass --ghidra explicitly when a real distribution is installed.
DEFAULT_GHIDRA_CANDIDATES = [
    r"D:/ghidra/rugra/ghidra/Ghidra/RuntimeScripts/Windows/support/analyzeHeadless.bat",
    r"C:/ghidra/support/analyzeHeadless.bat",
    r"D:/ghidra/support/analyzeHeadless.bat",
]

def resolve_default_ghidra():
    for p in DEFAULT_GHIDRA_CANDIDATES:
        if os.path.exists(p):
            return p
    return DEFAULT_GHIDRA_CANDIDATES[0]
REPO_ROOT = Path(__file__).resolve().parent.parent
HEADER_RE = re.compile(r'^/\* ---- 0x[0-9a-f]+: \S.+---- \*/')
TRAIL_INFO_RE = re.compile(r'^(INFO |WARN |ERROR |REPORT:|ANALYZING |HeadlessAnalyzer)')


def ghidra_version(ghidra_root):
    """Read application.properties next to the install root."""
    # ghidra_root is .../support/analyzeHeadless.bat → install root is .../Ghidra
    props = Path(ghidra_root).parents[1] / "application.properties"
    if not props.exists():
        # try the other layout: .../ghidra/Ghidra/application.properties
        for ancestor in Path(ghidra_root).parents:
            cand = ancestor / "application.properties"
            if cand.exists():
                props = cand
                break
    if not props.exists():
        return "unknown"
    for line in props.read_text(errors="replace").splitlines():
        if line.startswith("application.version="):
            return line.split("=", 1)[1].strip()
    return "unknown"


def validate_output(path):
    """Fail loud if the golden looks wrong. Returns (n_funcs, first_addr_or_None)."""
    if not path.exists():
        raise RuntimeError(f"output not created: {path}")
    text = path.read_text(encoding="utf-8", errors="replace")
    if not text.strip():
        raise RuntimeError("output is empty")
    lines = text.splitlines()
    # Must start with a function header (no leading INFO log noise).
    if not HEADER_RE.match(lines[0]):
        # find first header
        for i, ln in enumerate(lines[:50]):
            if HEADER_RE.match(ln):
                raise RuntimeError(
                    f"leading noise before first header at line {i+1}: {lines[0][:80]!r}")
        raise RuntimeError(f"first line is not a function header: {lines[0][:80]!r}")
    # Must NOT end with Ghidra INFO log noise.
    for ln in reversed(lines[-10:]):
        if ln.strip() and TRAIL_INFO_RE.match(ln.strip()):
            raise RuntimeError(f"trailing log noise in golden: {ln[:80]!r}")
    n_funcs = sum(1 for ln in lines if HEADER_RE.match(ln))
    if n_funcs == 0:
        raise RuntimeError("no function headers found")
    first = HEADER_RE.match(lines[0])
    return n_funcs, first.group(0)


def run(binary, output, ghidra_exe, keep_project, timeout):
    binary = Path(binary).resolve()
    output = Path(output).resolve()
    if not binary.exists():
        print(f"[!] binary not found: {binary}", file=sys.stderr)
        return 1
    if not Path(ghidra_exe).exists():
        print(f"[!] analyzeHeadless not found: {ghidra_exe}", file=sys.stderr)
        print("    pass --ghidra <path-to-analyzeHeadless>", file=sys.stderr)
        return 1

    script = REPO_ROOT / "tools" / "ghidra_decompile_all.py"
    project_dir = Path(tempfile.mkdtemp(prefix="ghidra_proj_"))
    proj_name = "regen_proj"

    # analyzeHeadless postScript args must come AFTER the script name and are
    # passed verbatim. We pass the absolute output path.
    cmd = [
        ghidra_exe,
        str(project_dir), proj_name,
        "-import", str(binary),
        "-scriptPath", str(REPO_ROOT / "tools"),
        "-postScript", "ghidra_decompile_all.py", str(output),
        "-deleteProject",   # hermetic: no leftover project state
    ]
    print(f"[regen] binary : {binary}")
    print(f"[regen] output : {output}")
    print(f"[regen] ghidra : {ghidra_exe} (version {ghidra_version(ghidra_exe)})")
    print(f"[regen] project: {project_dir} (deleted after)")
    print(f"[regen] running analyzeHeadless (timeout {timeout}s)...")

    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True,
            timeout=timeout, encoding="utf-8", errors="replace",
        )
    except subprocess.TimeoutExpired:
        print(f"[!] Ghidra timed out after {timeout}s", file=sys.stderr)
        return 1
    finally:
        if not keep_project and project_dir.exists():
            shutil.rmtree(project_dir, ignore_errors=True)

    # Look for our sentinel summary line in stdout.
    done_line = None
    for ln in proc.stdout.splitlines():
        if ln.startswith("GHIDRA_DECOMP_DONE"):
            done_line = ln
            break
    if done_line is None:
        print("[!] did not see GHIDRA_DECOMP_DONE sentinel", file=sys.stderr)
        print("---- Ghidra stdout (last 30 lines) ----", file=sys.stderr)
        for ln in proc.stdout.splitlines()[-30:]:
            print("    " + ln, file=sys.stderr)
        print("---- Ghidra stderr (last 20 lines) ----", file=sys.stderr)
        for ln in proc.stderr.splitlines()[-20:]:
            print("    " + ln, file=sys.stderr)
        return 1

    try:
        n_funcs, first_header = validate_output(output)
    except RuntimeError as e:
        print(f"[!] output validation failed: {e}", file=sys.stderr)
        return 1

    print(f"[regen] {done_line}")
    print(f"[regen] validated: {n_funcs} functions, first header: {first_header}")
    print(f"[regen] OK → {output}")
    return 0


def main():
    ap = argparse.ArgumentParser(
        description="Reproducible Ghidra golden-output regeneration")
    ap.add_argument("--binary", required=True, help="binary to decompile")
    ap.add_argument("--output", default=None,
                    help="output .c path (default tests/golden/ghidra_<binname>.c)")
    ap.add_argument("--ghidra", default=None,
                    help="path to analyzeHeadless(.bat); auto-detected if omitted")
    ap.add_argument("--keep-project", action="store_true",
                    help="keep the temp Ghidra project (debug)")
    ap.add_argument("--timeout", type=int, default=600,
                    help="Ghidra timeout in seconds (default 600)")
    args = ap.parse_args()

    if args.output is None:
        binname = Path(args.binary).stem
        args.output = str(REPO_ROOT / "tests" / "golden" / f"ghidra_{binname}.c")
    if args.ghidra is None:
        args.ghidra = resolve_default_ghidra()

    sys.exit(run(args.binary, args.output, args.ghidra,
                 args.keep_project, args.timeout))


if __name__ == "__main__":
    main()
