//! Reachability-based control flow tracking.
//!
//! Faithful to Ghidra's `FlowInfo` (flow.cc/flow.hh). Replaces Rugra's
//! linear-scan approach (disassemble → lift → inject_raw_ops) with
//! address-list-driven flow tracking that only decodes reachable code.

use crate::address::Address;
use crate::disasm::{Disassembler, Instruction};
use crate::disasm::x86_lift::X86Lifter;
use crate::funcdata::Funcdata;
use crate::loadimage::LoadImage;
use crate::opcodes::OpCode;

/// Record of a visited instruction (flow.hh:77-80 VisitStat).
#[derive(Clone, Debug)]
struct VisitStat {
    /// Sequence number order of the first PcodeOp generated by this instruction.
    order: u32,
    /// Instruction byte length.
    size: usize,
}

/// Reachability-based flow tracker. Faithful to `FlowInfo` (flow.hh:58-169).
///
/// Phase 1 (`generate_ops`): Decode instructions following control flow
/// from the entry point, building a work-list of reachable addresses.
/// Phase 2 (`generate_blocks`): Reuse Rugra's `build_blocks_from_ops`.
///
/// **Not yet ported**: jump-table inline expansion (tablelist/recoverJumpTables),
/// truncatedFlow/partial clone, inlineFlow/subfunction inlining, P-code injection.
pub struct FlowInfo<'a> {
    fd: &'a mut Funcdata,
    load_image: &'a dyn LoadImage,
    disassembler: &'a mut dyn Disassembler,
    lifter: &'a mut X86Lifter,
    /// Work-list of addresses to process (LIFO stack). flow.hh:82 addrlist.
    addrlist: Vec<Address>,
    /// Visited instruction map (flow.hh:84 visited).
    visited: std::collections::BTreeMap<u64, VisitStat>,
    /// Instruction count limit (flow.hh:96 insn_max).
    insn_max: u64,
    /// Instruction count (flow.hh:95 insn_count).
    insn_count: u64,
    /// Flow range [baddr, eaddr).
    baddr: u64,
    eaddr: u64,
    /// Actual min/max address seen.
    minaddr: u64,
    maxaddr: u64,
}

impl<'a> FlowInfo<'a> {
    // Ghidra: flow.hh:106 FlowInfo::FlowInfo
    pub fn new(
        fd: &'a mut Funcdata,
        load_image: &'a dyn LoadImage,
        disassembler: &'a mut dyn Disassembler,
        lifter: &'a mut X86Lifter,
        baddr: u64,
        eaddr: u64,
    ) -> Self {
        Self {
            fd,
            load_image,
            disassembler,
            lifter,
            addrlist: Vec::new(),
            visited: std::collections::BTreeMap::new(),
            insn_max: 100000, // Ghidra default max_instructions
            insn_count: 0,
            baddr,
            eaddr,
            minaddr: u64::MAX,
            maxaddr: 0,
        }
    }

    /// Set the maximum instruction limit. Faithful to `setMaximumInstructions`.
    // Ghidra: flow.hh:148 FlowInfo::setMaximumInstructions
    pub fn set_max_instructions(&mut self, max: u64) {
        self.insn_max = max;
    }

    /// Generate P-code ops by following control flow from the entry point.
    /// Faithful to `FlowInfo::generateOps` (flow.cc:785-822).
    /// Phase 2: jump-table recovery via recoverJumpTables.
    // Ghidra: flow.cc:785 FlowInfo::generateOps
    pub fn generate_ops(&mut self, entry: Address) {
        // Seed with entry address (flow.cc:787).
        self.addrlist.push(entry);

        // Phase 1: linear flow tracking (flow.cc:792-793).
        while !self.addrlist.is_empty() {
            self.fallthru();
        }

        // Phase 2: jump-table recovery (flow.cc:796-821).
        // Collect BRANCHIND ops found during Phase 1, recover their jump
        // tables, and push newly discovered addresses to addrlist.
        loop {
            // Collect all BRANCHIND ops currently alive.
            let branchinds: Vec<crate::op::PcodeOpRef> = self.collect_branchinds();
            if branchinds.is_empty() {
                break;
            }

            // Recover jump tables for each BRANCHIND.
            let mut new_addresses: Vec<Address> = Vec::new();
            for bi_ref in &branchinds {
                // Check if already has a jump table.
                let bi_addr = bi_ref.0.read().unwrap().get_addr().as_u64();
                let already = self.fd.jump_tables.iter().any(|jt| {
                    jt.read().unwrap().get_op_address().as_u64() == bi_addr
                });
                if already {
                    // Use existing table entries.
                    if let Some(jt_arc) = self.fd.jump_tables.iter().find(|jt| {
                        jt.read().unwrap().get_op_address().as_u64() == bi_addr
                    }) {
                        let jt = jt_arc.read().unwrap();
                        for i in 0..jt.num_entries() {
                            new_addresses.push(jt.get_address_by_index(i));
                        }
                    }
                    continue;
                }

                // Try recovery (jumptable.rs::try_recover).
                if let Some(jt) = crate::jumptable::try_recover(&bi_ref.0, self.fd) {
                    let jt_arc = std::sync::Arc::new(std::sync::RwLock::new(jt));
                    let jt_copy = jt_arc.read().unwrap();
                    for i in 0..jt_copy.num_entries() {
                        new_addresses.push(jt_copy.get_address_by_index(i));
                    }
                    drop(jt_copy);
                    self.fd.jump_tables.push(jt_arc);
                }
            }

            // Push newly discovered addresses and trace them (flow.cc:806-809).
            for addr in &new_addresses {
                self.new_address(*addr);
            }
            while !self.addrlist.is_empty() {
                self.fallthru();
            }

            // Check if any new BRANCHINDs appeared (multistage, flow.cc:814).
            let new_branchinds = self.collect_branchinds();
            if new_branchinds.len() <= branchinds.len() {
                break; // No new indirect jumps → done.
            }
        }
    }

    // RUGRA-GLUE: 收集 alive BRANCHIND ops（Ghidra 内联在 generateOps 的 tablelist 循环中）。
    /// Collect all alive BRANCHIND ops (for tablelist processing).
    fn collect_branchinds(&self) -> Vec<crate::op::PcodeOpRef> {
        self.fd.obank.alivelist.iter()
            .filter(|r| r.0.read().unwrap().opcode == crate::opcodes::OpCode::CPUI_BRANCHIND)
            .map(|r| crate::op::PcodeOpRef(r.0.clone()))
            .collect()
    }

    // Ghidra: flow.cc:198 FlowInfo::newAddress
    /// Add a new address to the work-list (flow.cc newAddress, ~:198-215).
    fn new_address(&mut self, addr: Address) {
        // Only add if within flow range and not already visited.
        let a = addr.as_u64();
        if a < self.baddr || a >= self.eaddr {
            return;
        }
        if self.visited.contains_key(&a) {
            return;
        }
        self.addrlist.push(addr);
    }

    /// Process sequential instructions from addrlist until a terminator
    /// or already-visited address is hit. Faithful to `FlowInfo::fallthru`
    /// (flow.cc:545-580).
    // Ghidra: flow.cc:545 FlowInfo::fallthru
    fn fallthru(&mut self) {
        // Check if next address is worth processing (setFallthruBound).
        if !self.set_fallthru_bound() {
            return;
        }

        let mut is_fallthru = true;
        while is_fallthru && !self.addrlist.is_empty() {
            let curaddr = self.addrlist.pop().unwrap();
            is_fallthru = self.process_instruction(curaddr);

            if !is_fallthru {
                break;
            }

            if self.addrlist.is_empty() {
                break;
            }

            // Check boundary (flow.cc:560-574).
            let next = self.addrlist.last().unwrap().as_u64();
            let bound = self.current_bound();
            if bound > 0 && next >= bound {
                if bound == self.eaddr {
                    // Out of bounds — stop.
                    self.addrlist.pop();
                    return;
                }
                // Hit an already-visited address boundary.
                // set_fallthru_bound will handle dedup on next iteration.
                if !self.set_fallthru_bound() {
                    return;
                }
            }
        }
    }

    /// Check if the next address in addrlist is processable.
    /// Returns false if already visited or out of bounds.
    /// Faithful to `setFallthruBound` (flow.cc:489-513).
    // Ghidra: flow.cc:489 FlowInfo::setFallthruBound
    fn set_fallthru_bound(&mut self) -> bool {
        if self.addrlist.is_empty() {
            return false;
        }
        let addr = self.addrlist.last().unwrap().as_u64();

        // Check visited map (flow.cc:505-510).
        if let Some(stat) = self.visited.get(&addr) {
            // Already visited — pop and return false.
            self.addrlist.pop();
            return false;
        }

        // Check upper bound for reinterpreted addresses (flow.cc:507-509).
        // If addr falls within a previously visited instruction's range,
        // it's an off-cut (reinterpreted) — skip it.
        if let Some((_, stat)) = self.visited.range(..addr).next_back() {
            // This entry's address + size must be <= addr (otherwise overlap).
            // Since BTreeMap keys are the addresses, the predecessor's
            // [key, key+size) must not contain addr.
            // We need the predecessor's key + size.
            // range(..addr) gives entries with key < addr.
            let _ = stat; // We handle this below with full check.
        }
        // Full overlap check: any visited instruction [k, k+size) containing addr?
        for (&k, stat) in self.visited.range(..=addr).rev() {
            if k + stat.size as u64 > addr && k <= addr {
                // addr is inside a previously decoded instruction → reinterpreted.
                self.addrlist.pop();
                return false;
            }
            if k + stat.size as u64 <= addr {
                break; // No overlap possible with earlier entries.
            }
        }

        true
    }

    /// Get the current boundary address (next visited instruction after addrlist top).
    // RUGRA-GLUE: 辅助方法，Ghidra 内联在 setFallthruBound/fallthru 中。
    fn current_bound(&self) -> u64 {
        if self.addrlist.is_empty() {
            return self.eaddr;
        }
        let addr = self.addrlist.last().unwrap().as_u64();
        // Find the next visited instruction after addr.
        match self.visited.range(addr + 1..).next() {
            Some((&k, _)) => k,
            None => self.eaddr,
        }
    }

    /// Decode a single instruction, generate P-code, and analyze control flow.
    /// Returns true if execution falls through to the next instruction.
    /// Faithful to `processInstruction` (flow.cc:383-482).
    // Ghidra: flow.cc:383 FlowInfo::processInstruction
    fn process_instruction(&mut self, addr: Address) -> bool {
        // Instruction count limit (flow.cc:387).
        if self.insn_count >= self.insn_max {
            eprintln!("[FLOW] Too many instructions (limit {})", self.insn_max);
            return false;
        }
        self.insn_count += 1;

        // Load instruction bytes (up to 15 for x86-64).
        let code = match self.load_image.load_fill(15, addr) {
            Ok(bytes) => bytes,
            Err(_) => {
                eprintln!("[FLOW] Cannot load bytes at {:#x}", addr.as_u64());
                return false;
            }
        };

        // Decode single instruction (oneInstruction equivalent).
        let (inst, step) = match self.disassembler.disassemble_one(&code, addr) {
            Ok(result) => result,
            Err(e) => {
                eprintln!("[FLOW] Decode error at {:#x}: {}", addr.as_u64(), e);
                return false;
            }
        };

        // Record visited (flow.cc:468-469).
        let order = self.fd.obank.alivelist.len() as u32;
        self.visited.insert(addr.as_u64(), VisitStat {
            order,
            size: step,
        });

        // Update min/max addr (flow.cc:470-471).
        let a = addr.as_u64();
        if a < self.minaddr { self.minaddr = a; }
        if a > self.maxaddr { self.maxaddr = a; }

        // Lift to P-code ops (flow.cc:454 translate->oneInstruction).
        let raw_ops = self.lifter.lift(&inst);
        let num_ops_before = self.fd.obank.alivelist.len();

        // Inject into Funcdata (reuse inject_raw_ops_single logic).
        self.fd.inject_raw_ops_single(&raw_ops, addr);

        // Analyze control flow of the new ops (xrefControlFlow).
        let is_fallthru = self.xref_control_flow(addr, step, num_ops_before);

        is_fallthru
    }

    /// Analyze the control-flow ops generated by the last instruction.
    /// Returns true if execution falls through.
    /// Faithful to `xrefControlFlow` (flow.cc:264-372).
    // Ghidra: flow.cc:264 FlowInfo::xrefControlFlow
    fn xref_control_flow(&mut self, addr: Address, step: usize, ops_start: usize) -> bool {
        let ops_end = self.fd.obank.alivelist.len();
        let mut is_fallthru = true;

        for i in ops_start..ops_end {
            let op_ref = &self.fd.obank.alivelist[i];
            let op = op_ref.0.read().unwrap();
            match op.opcode {
                OpCode::CPUI_BRANCH => {
                    // Direct branch. Target from in(0) constant varnode.
                    if let Some(in0) = op.inrefs.get(0) {
                        let target = in0.read().unwrap().get_offset();
                        if target == addr.as_u64() + step as u64 {
                            // Branch to next instruction = fallthrough.
                            // is_fallthru stays true.
                        } else {
                            // Push target to addrlist (flow.cc:312).
                            self.addrlist.push(Address::new(target));
                            is_fallthru = false;
                        }
                    } else {
                        is_fallthru = false;
                    }
                }
                OpCode::CPUI_CBRANCH => {
                    // Conditional branch: both targets are reachable.
                    // Push the branch target (flow.cc:312).
                    if let Some(in0) = op.inrefs.get(0) {
                        let target = in0.read().unwrap().get_offset();
                        if target != addr.as_u64() + step as u64 {
                            self.addrlist.push(Address::new(target));
                        }
                    }
                    // Fallthrough target is pushed by the caller (process_instruction
                    // pushes addr+step via the return value).
                }
                OpCode::CPUI_BRANCHIND => {
                    // Indirect branch (switch/jump table). Not yet supported
                    // in flow tracking — would need recoverJumpTables.
                    // For now, mark as non-fallthru (flow stops here).
                    eprintln!("[FLOW] BRANCHIND at {:#x} — jump-table recovery not yet in flow", addr.as_u64());
                    is_fallthru = false;
                }
                OpCode::CPUI_RETURN => {
                    is_fallthru = false;
                }
                OpCode::CPUI_CALL | OpCode::CPUI_CALLIND => {
                    // Call: setup callspecs would go here (flow.cc:330-348).
                    // Rugra's ActionFuncLink does this post-hoc.
                    // Calls are fallthru (return address continues flow).
                }
                _ => {}
            }
        }

        // If fallthru, push next instruction address (flow.cc:458).
        if is_fallthru {
            self.addrlist.push(Address::new(addr.as_u64() + step as u64));
        }

        is_fallthru
    }
}

/// Entry point: follow flow from entry address, generating P-code ops and CFG.
/// Faithful to `Funcdata::followFlow` (funcdata_op.cc:756-783).
///
/// Replaces the three-stage linear scan (disassemble → lift → inject_raw_ops)
/// with reachability-driven flow tracking.
// Ghidra: funcdata_op.cc:756 Funcdata::followFlow
pub fn follow_flow(
    fd: &mut Funcdata,
    load_image: &dyn LoadImage,
    disassembler: &mut dyn Disassembler,
    lifter: &mut X86Lifter,
    entry: Address,
    eaddr: u64,
) {
    let baddr = entry.as_u64();
    let mut flow = FlowInfo::new(fd, load_image, disassembler, lifter, baddr, eaddr);
    flow.generate_ops(entry);
    // generateBlocks: build basic blocks from all alive ops.
    flow.fd.build_blocks_from_alive();
}
