//! Reachability-based control flow tracking.
//!
//! Faithful to Ghidra's `FlowInfo` (flow.cc/flow.hh). Replaces Rugra's
//! linear-scan approach (disassemble → lift → inject_raw_ops) with
//! address-list-driven flow tracking that only decodes reachable code.

use crate::address::Address;
use crate::disasm::{Disassembler, Instruction};
use crate::disasm::x86_lift::X86Lifter;
use crate::funcdata::Funcdata;
use crate::loadimage::LoadImage;
use crate::opcodes::OpCode;
use crate::op::pcodeop_flags;

/// Flow-following option/property flag bits. Faithful to the anonymous enum
/// in flow.hh:60-74.
// Ghidra: flow.hh:60 FlowInfo::(anonymous enum)
pub mod flow_flags {
    /// Ignore/truncate flow into addresses out of the specified range.
    pub const IGNORE_OUTOFBOUNDS: u32 = 1;
    /// Treat unimplemented instructions as a NOP (no operation).
    pub const IGNORE_UNIMPLEMENTED: u32 = 2;
    /// Throw an exception for flow into addresses out of the specified range.
    pub const ERROR_OUTOFBOUNDS: u32 = 4;
    /// Throw an exception for flow into unimplemented instructions.
    pub const ERROR_UNIMPLEMENTED: u32 = 8;
    /// Throw an exception for flow into previously encountered data at a different cut.
    pub const ERROR_REINTERPRETED: u32 = 0x10;
    /// Throw an exception if too many instructions are encountered.
    pub const ERROR_TOOMANYINSTRUCTIONS: u32 = 0x20;
    /// Indicate we have encountered unimplemented instructions.
    pub const UNIMPLEMENTED_PRESENT: u32 = 0x40;
    /// Indicate we have encountered flow into unaccessible data.
    pub const BADDATA_PRESENT: u32 = 0x80;
    /// Indicate we have encountered flow out of the specified range.
    pub const OUTOFBOUNDS_PRESENT: u32 = 0x100;
    /// Indicate we have encountered reinterpreted data.
    pub const REINTERPRETED_PRESENT: u32 = 0x200;
    /// Indicate the maximum instruction threshold was reached.
    pub const TOOMANYINSTRUCTIONS_PRESENT: u32 = 0x400;
    /// Indicate a CALL was converted to a BRANCH and some code may be unreachable.
    pub const POSSIBLE_UNREACHABLE: u32 = 0x1000;
    /// Indicate flow is being generated to in-line (a function).
    pub const FLOW_FORINLINE: u32 = 0x2000;
    /// Indicate that any jump table recovery should record the table structure.
    pub const RECORD_JUMPLOADS: u32 = 0x4000;
}

/// Record of a visited instruction (flow.hh:77-80 VisitStat).
#[derive(Clone, Debug)]
struct VisitStat {
    /// Sequence number order of the first PcodeOp generated by this instruction.
    order: u32,
    /// Instruction byte length.
    size: usize,
}

/// Reachability-based flow tracker. Faithful to `FlowInfo` (flow.hh:58-169).
///
/// Phase 1 (`generate_ops`): Decode instructions following control flow
/// from the entry point, building a work-list of reachable addresses.
/// Phase 2 (`generate_blocks`): Reuse Rugra's `build_blocks_from_ops`.
///
/// **Not yet ported**: jump-table inline expansion (tablelist/recoverJumpTables),
/// truncatedFlow/partial clone, inlineFlow/subfunction inlining, P-code injection.
pub struct FlowInfo<'a> {
    fd: &'a mut Funcdata,
    load_image: &'a dyn LoadImage,
    disassembler: &'a mut dyn Disassembler,
    lifter: &'a mut X86Lifter,
    /// Work-list of addresses to process (LIFO stack). flow.hh:82 addrlist.
    addrlist: Vec<Address>,
    /// Addresses which are permanently unprocessed (flow.hh:87 unprocessed).
    unprocessed: Vec<Address>,
    /// Visited instruction map (flow.hh:84 visited).
    visited: std::collections::BTreeMap<u64, VisitStat>,
    /// Instruction count limit (flow.hh:96 insn_max).
    insn_max: u64,
    /// Instruction count (flow.hh:95 insn_count).
    insn_count: u64,
    /// Flow range [baddr, eaddr).
    baddr: u64,
    eaddr: u64,
    /// Actual min/max address seen.
    minaddr: u64,
    maxaddr: u64,
    /// Boolean options for flow following (flow.hh:101 flags).
    flags: u32,
}

impl<'a> FlowInfo<'a> {
    // Ghidra: flow.hh:106 FlowInfo::FlowInfo
    pub fn new(
        fd: &'a mut Funcdata,
        load_image: &'a dyn LoadImage,
        disassembler: &'a mut dyn Disassembler,
        lifter: &'a mut X86Lifter,
        baddr: u64,
        eaddr: u64,
    ) -> Self {
        Self {
            fd,
            load_image,
            disassembler,
            lifter,
            addrlist: Vec::new(),
            unprocessed: Vec::new(),
            visited: std::collections::BTreeMap::new(),
            insn_max: 100000, // Ghidra default max_instructions
            insn_count: 0,
            baddr,
            eaddr,
            minaddr: u64::MAX,
            maxaddr: 0,
            flags: 0,
        }
    }

    /// Set the maximum instruction limit. Faithful to `setMaximumInstructions`.
    // Ghidra: flow.hh:148 FlowInfo::setMaximumInstructions
    pub fn set_max_instructions(&mut self, max: u64) {
        self.insn_max = max;
    }

    /// Establish the flow bounds. Faithful to inline `setRange`
    /// (flow.hh:145).
    // Ghidra: flow.hh:145 FlowInfo::setRange
    pub fn set_range(&mut self, b: u64, e: u64) {
        self.baddr = b;
        self.eaddr = e;
    }

    /// Enable a specific flow option. Faithful to inline `setFlags`
    /// (flow.hh:147).
    // Ghidra: flow.hh:147 FlowInfo::setFlags
    pub fn set_flags(&mut self, val: u32) {
        self.flags |= val;
    }

    /// Disable a specific flow option. Faithful to inline `clearFlags`
    /// (flow.hh:148).
    // Ghidra: flow.hh:148 FlowInfo::clearFlags
    pub fn clear_flags(&mut self, val: u32) {
        self.flags &= !val;
    }

    /// Get the number of bytes covered by the flow. Faithful to inline
    /// `getSize` (flow.hh:160).
    // Ghidra: flow.hh:160 FlowInfo::getSize
    pub fn get_size(&self) -> u64 {
        // Ghidra returns maxaddr - minaddr; Rugra uses u64 sentinel for "no min".
        if self.minaddr == u64::MAX {
            0
        } else {
            self.maxaddr.saturating_sub(self.minaddr)
        }
    }

    /// Has the given instruction (address) been seen in flow. Faithful to
    /// inline `seenInstruction` (flow.hh:108).
    // Ghidra: flow.hh:108 FlowInfo::seenInstruction
    pub fn seen_instruction(&self, addr: Address) -> bool {
        self.visited.contains_key(&addr.as_u64())
    }

    /// Are there possible unreachable ops. Faithful to inline
    /// `hasPossibleUnreachable` (flow.hh:105).
    // Ghidra: flow.hh:105 FlowInfo::hasPossibleUnreachable
    pub fn has_possible_unreachable(&self) -> bool {
        (self.flags & flow_flags::POSSIBLE_UNREACHABLE) != 0
    }

    /// Mark that there may be unreachable ops. Faithful to inline
    /// `setPossibleUnreachable` (flow.hh:106).
    // Ghidra: flow.hh:106 FlowInfo::setPossibleUnreachable
    pub fn set_possible_unreachable(&mut self) {
        self.flags |= flow_flags::POSSIBLE_UNREACHABLE;
    }

    /// Does this flow have injections. Faithful to inline `hasInject`
    /// (flow.hh:161). Rugra does not yet model an `injectlist`, so this is
    /// always false; provided for API parity.
    // Ghidra: flow.hh:161 FlowInfo::hasInject
    pub fn has_inject(&self) -> bool {
        false
    }

    /// Does this flow have unimplemented instructions. Faithful to inline
    /// `hasUnimplemented` (flow.hh:162).
    // Ghidra: flow.hh:162 FlowInfo::hasUnimplemented
    pub fn has_unimplemented(&self) -> bool {
        (self.flags & flow_flags::UNIMPLEMENTED_PRESENT) != 0
    }

    /// Does this flow reach inaccessible data. Faithful to inline
    /// `hasBadData` (flow.hh:163).
    // Ghidra: flow.hh:163 FlowInfo::hasBadData
    pub fn has_bad_data(&self) -> bool {
        (self.flags & flow_flags::BADDATA_PRESENT) != 0
    }

    /// Does this flow flow out of bound. Faithful to inline `hasOutOfBounds`
    /// (flow.hh:164).
    // Ghidra: flow.hh:164 FlowInfo::hasOutOfBounds
    pub fn has_out_of_bounds(&self) -> bool {
        (self.flags & flow_flags::OUTOFBOUNDS_PRESENT) != 0
    }

    /// Does this flow reinterpret bytes. Faithful to inline `hasReinterpreted`
    /// (flow.hh:165).
    // Ghidra: flow.hh:165 FlowInfo::hasReinterpreted
    pub fn has_reinterpreted(&self) -> bool {
        (self.flags & flow_flags::REINTERPRETED_PRESENT) != 0
    }

    /// Does this flow have too many instructions. Faithful to inline
    /// `hasTooManyInstructions` (flow.hh:166).
    // Ghidra: flow.hh:166 FlowInfo::hasTooManyInstructions
    pub fn has_too_many_instructions(&self) -> bool {
        (self.flags & flow_flags::TOOMANYINSTRUCTIONS_PRESENT) != 0
    }

    /// Is this flow to be in-lined. Faithful to inline `isFlowForInline`
    /// (flow.hh:167).
    // Ghidra: flow.hh:167 FlowInfo::isFlowForInline
    pub fn is_flow_for_inline(&self) -> bool {
        (self.flags & flow_flags::FLOW_FORINLINE) != 0
    }

    /// Should jump table structure be recorded. Faithful to inline
    /// `doesJumpRecord` (flow.hh:168).
    // Ghidra: flow.hh:168 FlowInfo::doesJumpRecord
    pub fn does_jump_record(&self) -> bool {
        (self.flags & flow_flags::RECORD_JUMPLOADS) != 0
    }

    /// Clear any discovered flow properties. Faithful to `clearProperties`
    /// (flow.cc:78-83). Resets the presence flags and the instruction
    /// counter, preparing for a fresh pass over the function.
    // Ghidra: flow.cc:78 FlowInfo::clearProperties
    pub fn clear_properties(&mut self) {
        self.flags &= !(flow_flags::UNIMPLEMENTED_PRESENT
            | flow_flags::BADDATA_PRESENT
            | flow_flags::OUTOFBOUNDS_PRESENT);
        self.insn_count = 0;
    }

    /// Generate warning message or throw exception for given flow that is
    /// out of bounds. Faithful to `handleOutOfBounds` (flow.cc:519-540).
    /// Rugra does not throw — it logs a warning and sets the
    /// `OUTOFBOUNDS_PRESENT` flag unless `IGNORE_OUTOFBOUNDS` is set.
    // Ghidra: flow.cc:519 FlowInfo::handleOutOfBounds
    fn handle_out_of_bounds(&mut self, fromaddr: Address, toaddr: Address) {
        if (self.flags & flow_flags::IGNORE_OUTOFBOUNDS) != 0 {
            return;
        }
        let msg = format!(
            "Function flow out of bounds: {:#x} flows to {:#x}",
            fromaddr.as_u64(),
            toaddr.as_u64()
        );
        if (self.flags & flow_flags::ERROR_OUTOFBOUNDS) == 0 {
            // data.warning(msg, toaddr);
            eprintln!("[FLOW] {}: {}", self.fd.name, msg);
            if !self.has_out_of_bounds() {
                self.flags |= flow_flags::OUTOFBOUNDS_PRESENT;
                self.fd.warning_header("Function flows out of bounds");
            }
        } else {
            // Ghidra throws LowlevelError; Rugra logs at error level instead.
            eprintln!("[FLOW] ERROR: {}: {}", self.fd.name, msg);
        }
    }

    /// Generate warning message or exception for a reinterpreted address.
    /// Faithful to `reinterpreted` (flow.cc:606-629). A set of bytes is
    /// reinterpreted if there are at least two different interpretations of
    /// the bytes as instructions. Rugra logs and sets the
    /// `REINTERPRETED_PRESENT` flag instead of throwing.
    // Ghidra: flow.cc:606 FlowInfo::reinterpreted
    fn reinterpreted(&mut self, addr: Address) {
        // Find the previously visited instruction whose tail overlaps addr.
        let mut addr2: Option<u64> = None;
        for (&k, _stat) in self.visited.range(..=addr.as_u64()).rev() {
            addr2 = Some(k);
            break;
        }
        let addr2 = match addr2 {
            Some(a) => a,
            None => return, // Should never happen.
        };
        let msg = format!(
            "Instruction at ({:#x}) overlaps instruction at ({:#x})",
            addr.as_u64(),
            addr2
        );
        if (self.flags & flow_flags::ERROR_REINTERPRETED) != 0 {
            eprintln!("[FLOW] ERROR: {}: {}", self.fd.name, msg);
            return;
        }
        if (self.flags & flow_flags::REINTERPRETED_PRESENT) == 0 {
            self.flags |= flow_flags::REINTERPRETED_PRESENT;
            self.fd.warning_header(&msg);
        }
    }

    /// An artificial halt is a special form of RETURN op. Faithful to
    /// `artificialHalt` (flow.cc:592-601). The op is annotated with the
    /// desired type of artificial halt:
    ///   - badinstruction (`PcodeOp::badinstruction`)
    ///   - unimplemented (`PcodeOp::unimplemented`)
    ///   - missing/truncated (`PcodeOp::missing`)
    ///   - noreturn (`PcodeOp::noreturn`)
    /// Returns the new RETURN op. The op is left in the dead list (Ghidra
    /// inserts via `data.newOp`, which is dead until `opInsert`).
    // Ghidra: flow.cc:592 FlowInfo::artificialHalt
    fn artificial_halt(&mut self, addr: Address, flag: u32) -> crate::op::PcodeOpRef {
        let haltop = self.fd.new_op(1, addr);
        self.fd.op_set_opcode(&haltop, OpCode::CPUI_RETURN);
        let c = self.fd.new_constant(4, 1);
        self.fd.op_set_input(&haltop, c, 0);
        if flag != 0 {
            self.fd.op_mark_halt(&haltop, flag);
        }
        haltop
    }

    /// Test if the given p-code op is a member of an array. Faithful to
    /// `isInArray` (flow.cc:776-783). This is a static helper in Ghidra used
    /// by `recoverJumpTables` to dedup BRANCHIND ops that need to be retried.
    // Ghidra: flow.cc:776 FlowInfo::isInArray
    fn is_in_array(
        array: &[crate::op::PcodeOpRef],
        op: &crate::op::PcodeOpRef,
    ) -> bool {
        array.iter().any(|x| std::sync::Arc::ptr_eq(&x.0, &op.0))
    }

    /// Delete any remaining ops at the end of the instruction (because they
    /// have been predetermined to be dead). Faithful to `deleteRemainingOps`
    /// (flow.cc:240-248). Ghidra walks the raw dead list from `oiter` to
    /// `endDead()` calling `opDestroyRaw`; Rugra uses `op_destroy` which
    /// unlinks the op from input Varnodes and marks it dead.
    // Ghidra: flow.cc:240 FlowInfo::deleteRemainingOps
    fn delete_remaining_ops_from(&mut self, start_idx: usize) {
        // Snapshot the tail of the alive list so we can drain without
        // upsetting the borrow checker (op_destroy mutates the list).
        let to_remove: Vec<crate::op::PcodeOpRef> =
            self.fd.obank.alivelist[start_idx..].to_vec();
        for op in &to_remove {
            self.fd.op_destroy(op);
        }
    }

    /// A function is in the EZ model if it is a straight-line leaf function.
    /// Faithful to `checkEZModel` (flow.cc:1157-1167). Returns true if this
    /// flow contains no CALL or BRANCH ops.
    // Ghidra: flow.cc:1157 FlowInfo::checkEZModel
    pub fn check_ez_model(&self) -> bool {
        for op_ref in &self.fd.obank.alivelist {
            let op = op_ref.0.read().unwrap();
            match op.opcode {
                OpCode::CPUI_BRANCH
                | OpCode::CPUI_CBRANCH
                | OpCode::CPUI_BRANCHIND
                | OpCode::CPUI_CALL
                | OpCode::CPUI_CALLIND
                | OpCode::CPUI_RETURN => return false,
                _ => {}
            }
        }
        true
    }

    /// Treat an indirect jump (BRANCHIND) whose jumptable could not be
    /// recovered as a CALLIND or RETURN instead. Faithful to
    /// `truncateIndirectJump` (flow.cc:727-769). For `fail_return` the
    /// BRANCHIND becomes a RETURN; otherwise it becomes a CALLIND with an
    /// associated FuncCallSpecs and an artificial halt after it.
    ///
    /// Rugra notes: full FuncCallSpecs setup (`setupCallindSpecs`) and the
    /// JumpTable::RecoveryMode enum are not yet modelled — callers pass the
    /// canonical fail modes via the `fail_mode` byte (0 = fail_thunk,
    /// 1 = fail_callother, 2 = fail_return, 3 = default).
    // Ghidra: flow.cc:727 FlowInfo::truncateIndirectJump
    pub fn truncate_indirect_jump(&mut self, op: &crate::op::PcodeOpRef, fail_mode: u8) {
        let addr = {
            let o = op.0.read().unwrap();
            o.get_addr()
        };
        if fail_mode == 2 {
            // JumpTable::fail_return: turn the jump into a RETURN.
            self.fd.op_set_opcode(op, OpCode::CPUI_RETURN);
            eprintln!(
                "[FLOW] {}: Treating indirect jump at {:#x} as return",
                self.fd.name,
                addr.as_u64()
            );
            return;
        }
        // Otherwise turn the jump into a CALLIND.
        self.fd.op_set_opcode(op, OpCode::CPUI_CALLIND);
        // Ghidra: setupCallindSpecs(op, NULL); (flow.cc:736) — FuncCallSpecs
        // plumbing is not yet ported; Rugra's ActionFuncLink does this
        // post-hoc. We log it so the gap is visible.
        eprintln!(
            "[FLOW] {}: NOTE setupCallindSpecs at {:#x} deferred to ActionFuncLink",
            self.fd.name,
            addr.as_u64()
        );
        let (return_type, _no_params, warn_msg) = match fail_mode {
            0 => (0u32, false, None), // fail_thunk
            1 => (
                pcodeop_flags::NORETURN,
                true,
                Some("Does not return"),
            ), // fail_callother
            _ => (0u32, false, Some("Treating indirect jump as call")), // default
        };
        if let Some(msg) = warn_msg {
            eprintln!("[FLOW] {}: {} at {:#x}", self.fd.name, msg, addr.as_u64());
        }
        // Ghidra: if (noParams) { fc->setInternal(...) } — FuncCallSpecs gap.
        // Create an artificial return (flow.cc:766-767) right after the op.
        let truncop = self.artificial_halt(addr, return_type);
        self.fd.op_insert_after(&truncop, op);
    }


    /// Generate P-code ops by following control flow from the entry point.
    /// Faithful to `FlowInfo::generateOps` (flow.cc:785-822).
    /// Phase 2: jump-table recovery via recoverJumpTables.
    // Ghidra: flow.cc:785 FlowInfo::generateOps
    pub fn generate_ops(&mut self, entry: Address) {
        // Seed with entry address (flow.cc:787).
        self.addrlist.push(entry);

        // Phase 1: linear flow tracking (flow.cc:792-793).
        while !self.addrlist.is_empty() {
            self.fallthru();
        }

        // Phase 2: jump-table recovery (flow.cc:796-821).
        // Collect BRANCHIND ops found during Phase 1, recover their jump
        // tables, and push newly discovered addresses to addrlist.
        loop {
            // Collect all BRANCHIND ops currently alive.
            let branchinds: Vec<crate::op::PcodeOpRef> = self.collect_branchinds();
            if branchinds.is_empty() {
                break;
            }

            // Recover jump tables for each BRANCHIND.
            let mut new_addresses: Vec<Address> = Vec::new();
            for bi_ref in &branchinds {
                // Check if already has a jump table.
                let bi_addr = bi_ref.0.read().unwrap().get_addr().as_u64();
                let already = self.fd.jump_tables.iter().any(|jt| {
                    jt.read().unwrap().get_op_address().as_u64() == bi_addr
                });
                if already {
                    // Use existing table entries.
                    if let Some(jt_arc) = self.fd.jump_tables.iter().find(|jt| {
                        jt.read().unwrap().get_op_address().as_u64() == bi_addr
                    }) {
                        let jt = jt_arc.read().unwrap();
                        for i in 0..jt.num_entries() {
                            new_addresses.push(jt.get_address_by_index(i));
                        }
                    }
                    continue;
                }

                // Try recovery (jumptable.rs::try_recover).
                if let Some(jt) = crate::jumptable::try_recover(&bi_ref.0, self.fd) {
                    let jt_arc = std::sync::Arc::new(std::sync::RwLock::new(jt));
                    let jt_copy = jt_arc.read().unwrap();
                    for i in 0..jt_copy.num_entries() {
                        new_addresses.push(jt_copy.get_address_by_index(i));
                    }
                    drop(jt_copy);
                    self.fd.jump_tables.push(jt_arc);
                }
            }

            // Push newly discovered addresses and trace them (flow.cc:806-809).
            for addr in &new_addresses {
                self.new_address(*addr);
            }
            while !self.addrlist.is_empty() {
                self.fallthru();
            }

            // Check if any new BRANCHINDs appeared (multistage, flow.cc:814).
            let new_branchinds = self.collect_branchinds();
            if new_branchinds.len() <= branchinds.len() {
                break; // No new indirect jumps → done.
            }
        }
    }

    // RUGRA-GLUE: 收集 alive BRANCHIND ops（Ghidra 内联在 generateOps 的 tablelist 循环中）。
    /// Collect all alive BRANCHIND ops (for tablelist processing).
    fn collect_branchinds(&self) -> Vec<crate::op::PcodeOpRef> {
        self.fd.obank.alivelist.iter()
            .filter(|r| r.0.read().unwrap().opcode == crate::opcodes::OpCode::CPUI_BRANCHIND)
            .map(|r| crate::op::PcodeOpRef(r.0.clone()))
            .collect()
    }

    // Ghidra: flow.cc:198 FlowInfo::newAddress
    /// Add a new address to the work-list (flow.cc newAddress, ~:198-215).
    /// Mirrors Ghidra's behavior: out-of-bounds addresses are reported via
    /// `handleOutOfBounds` and pushed to `unprocessed`; already-seen targets
    /// are skipped (Ghidra additionally marks the target op as a basic-block
    /// start, which Rugra handles post-hoc in `build_blocks_from_alive`).
    fn new_address(&mut self, addr: Address) {
        let a = addr.as_u64();
        // flow.cc:222-226: range check + handleOutOfBounds.
        if a < self.baddr || self.eaddr < a {
            self.handle_out_of_bounds(Address::new(self.baddr), addr);
            self.unprocessed.push(addr);
            return;
        }
        // flow.cc:228-233: if already seen, Ghidra marks the target op as a
        // basic block start. Rugra re-derives basic blocks from control-flow
        // ops at the end (build_blocks_from_alive), so this is a no-op.
        if self.seen_instruction(addr) {
            return;
        }
        self.addrlist.push(addr);
    }

    /// Process sequential instructions from addrlist until a terminator
    /// or already-visited address is hit. Faithful to `FlowInfo::fallthru`
    /// (flow.cc:545-580).
    // Ghidra: flow.cc:545 FlowInfo::fallthru
    fn fallthru(&mut self) {
        // Check if next address is worth processing (setFallthruBound).
        if !self.set_fallthru_bound() {
            return;
        }

        let mut is_fallthru = true;
        while is_fallthru && !self.addrlist.is_empty() {
            let curaddr = self.addrlist.pop().unwrap();
            is_fallthru = self.process_instruction(curaddr);

            if !is_fallthru {
                break;
            }

            if self.addrlist.is_empty() {
                break;
            }

            // Check boundary (flow.cc:560-574).
            let next = self.addrlist.last().unwrap().as_u64();
            let bound = self.current_bound();
            if bound > 0 && next >= bound {
                if bound == self.eaddr {
                    // Out of bounds — stop.
                    self.addrlist.pop();
                    return;
                }
                // Hit an already-visited address boundary.
                // set_fallthru_bound will handle dedup on next iteration.
                if !self.set_fallthru_bound() {
                    return;
                }
            }
        }
    }

    /// Check if the next address in addrlist is processable.
    /// Returns false if already visited or out of bounds.
    /// Faithful to `setFallthruBound` (flow.cc:489-513).
    // Ghidra: flow.cc:489 FlowInfo::setFallthruBound
    fn set_fallthru_bound(&mut self) -> bool {
        if self.addrlist.is_empty() {
            return false;
        }
        let addr = self.addrlist.last().unwrap().as_u64();

        // Check visited map (flow.cc:505-510).
        if let Some(stat) = self.visited.get(&addr) {
            // Already visited — pop and return false.
            self.addrlist.pop();
            return false;
        }

        // Check upper bound for reinterpreted addresses (flow.cc:507-509).
        // If addr falls within a previously visited instruction's range,
        // it's an off-cut (reinterpreted) — skip it.
        if let Some((_, stat)) = self.visited.range(..addr).next_back() {
            // This entry's address + size must be <= addr (otherwise overlap).
            // Since BTreeMap keys are the addresses, the predecessor's
            // [key, key+size) must not contain addr.
            // We need the predecessor's key + size.
            // range(..addr) gives entries with key < addr.
            let _ = stat; // We handle this below with full check.
        }
        // Full overlap check: any visited instruction [k, k+size) containing addr?
        for (&k, stat) in self.visited.range(..=addr).rev() {
            if k + stat.size as u64 > addr && k <= addr {
                // addr is inside a previously decoded instruction → reinterpreted
                // (flow.cc:504-505 calls reinterpreted(addr) here).
                self.reinterpreted(Address::new(addr));
                self.addrlist.pop();
                return false;
            }
            if k + stat.size as u64 <= addr {
                break; // No overlap possible with earlier entries.
            }
        }

        true
    }

    /// Get the current boundary address (next visited instruction after addrlist top).
    // RUGRA-GLUE: 辅助方法，Ghidra 内联在 setFallthruBound/fallthru 中。
    fn current_bound(&self) -> u64 {
        if self.addrlist.is_empty() {
            return self.eaddr;
        }
        let addr = self.addrlist.last().unwrap().as_u64();
        // Find the next visited instruction after addr.
        match self.visited.range(addr + 1..).next() {
            Some((&k, _)) => k,
            None => self.eaddr,
        }
    }

    /// Decode a single instruction, generate P-code, and analyze control flow.
    /// Returns true if execution falls through to the next instruction.
    /// Faithful to `processInstruction` (flow.cc:383-482).
    // Ghidra: flow.cc:383 FlowInfo::processInstruction
    fn process_instruction(&mut self, addr: Address) -> bool {
        // Instruction count limit (flow.cc:387).
        if self.insn_count >= self.insn_max {
            eprintln!("[FLOW] Too many instructions (limit {})", self.insn_max);
            return false;
        }
        self.insn_count += 1;

        // Load instruction bytes (up to 15 for x86-64).
        let code = match self.load_image.load_fill(15, addr) {
            Ok(bytes) => bytes,
            Err(_) => {
                eprintln!("[FLOW] Cannot load bytes at {:#x}", addr.as_u64());
                return false;
            }
        };

        // Decode single instruction (oneInstruction equivalent).
        let (inst, step) = match self.disassembler.disassemble_one(&code, addr) {
            Ok(result) => result,
            Err(e) => {
                eprintln!("[FLOW] Decode error at {:#x}: {}", addr.as_u64(), e);
                return false;
            }
        };

        // Record visited (flow.cc:468-469).
        let order = self.fd.obank.alivelist.len() as u32;
        self.visited.insert(addr.as_u64(), VisitStat {
            order,
            size: step,
        });

        // Update min/max addr (flow.cc:470-471).
        let a = addr.as_u64();
        if a < self.minaddr { self.minaddr = a; }
        if a > self.maxaddr { self.maxaddr = a; }

        // Lift to P-code ops via SLEIGH (flow.cc:454 translate->oneInstruction).
        let raw_ops = crate::disasm::sleigh_lift::SleighLifter::lift_from_func(
            &code[..step], addr.as_u64(), addr.as_u64(),
        );
        let num_ops_before = self.fd.obank.alivelist.len();

        // Inject into Funcdata (reuse inject_raw_ops_single logic).
        self.fd.inject_raw_ops_single(&raw_ops, addr);

        // Analyze control flow of the new ops (xrefControlFlow).
        let is_fallthru = self.xref_control_flow(addr, step, num_ops_before);

        is_fallthru
    }

    /// Analyze the control-flow ops generated by the last instruction.
    /// Returns true if execution falls through.
    /// Faithful to `xrefControlFlow` (flow.cc:264-372).
    // Ghidra: flow.cc:264 FlowInfo::xrefControlFlow
    fn xref_control_flow(&mut self, addr: Address, step: usize, ops_start: usize) -> bool {
        let ops_end = self.fd.obank.alivelist.len();
        let mut is_fallthru = true;

        for i in ops_start..ops_end {
            let op_ref = &self.fd.obank.alivelist[i];
            let op = op_ref.0.read().unwrap();
            match op.opcode {
                OpCode::CPUI_BRANCH => {
                    // Direct branch. Target from in(0) constant varnode.
                    if let Some(in0) = op.inrefs.get(0) {
                        let target = in0.read().unwrap().get_offset();
                        if target == addr.as_u64() + step as u64 {
                            // Branch to next instruction = fallthrough.
                            // is_fallthru stays true.
                        } else {
                            // Push target to addrlist (flow.cc:312).
                            self.addrlist.push(Address::new(target));
                            is_fallthru = false;
                        }
                    } else {
                        is_fallthru = false;
                    }
                }
                OpCode::CPUI_CBRANCH => {
                    // Conditional branch: both targets are reachable.
                    // Push the branch target (flow.cc:312).
                    if let Some(in0) = op.inrefs.get(0) {
                        let target = in0.read().unwrap().get_offset();
                        if target != addr.as_u64() + step as u64 {
                            self.addrlist.push(Address::new(target));
                        }
                    }
                    // Fallthrough target is pushed by the caller (process_instruction
                    // pushes addr+step via the return value).
                }
                OpCode::CPUI_BRANCHIND => {
                    // Indirect branch (switch/jump table). Not yet supported
                    // in flow tracking — would need recoverJumpTables.
                    // For now, mark as non-fallthru (flow stops here).
                    eprintln!("[FLOW] BRANCHIND at {:#x} — jump-table recovery not yet in flow", addr.as_u64());
                    is_fallthru = false;
                }
                OpCode::CPUI_RETURN => {
                    is_fallthru = false;
                }
                OpCode::CPUI_CALL | OpCode::CPUI_CALLIND => {
                    // Call: setup callspecs would go here (flow.cc:330-348).
                    // Rugra's ActionFuncLink does this post-hoc.
                    // Calls are fallthru (return address continues flow).
                }
                _ => {}
            }
        }

        // If fallthru, push next instruction address (flow.cc:458).
        if is_fallthru {
            self.addrlist.push(Address::new(addr.as_u64() + step as u64));
        }

        is_fallthru
    }
}

/// Entry point: follow flow from entry address, generating P-code ops and CFG.
/// Faithful to `Funcdata::followFlow` (funcdata_op.cc:756-783).
///
/// Replaces the three-stage linear scan (disassemble → lift → inject_raw_ops)
/// with reachability-driven flow tracking.
// Ghidra: funcdata_op.cc:756 Funcdata::followFlow
pub fn follow_flow(
    fd: &mut Funcdata,
    load_image: &dyn LoadImage,
    disassembler: &mut dyn Disassembler,
    lifter: &mut X86Lifter,
    entry: Address,
    eaddr: u64,
) {
    let baddr = entry.as_u64();
    let mut flow = FlowInfo::new(fd, load_image, disassembler, lifter, baddr, eaddr);
    flow.generate_ops(entry);
    // generateBlocks: build basic blocks from all alive ops.
    flow.fd.build_blocks_from_alive();
}
